version: '3.8'

name: markus

volumes:
  mysql-data:
    driver: local

services:
  mysql:
    container_name: markus-nextjs
    platform: linux/amd64
    restart: always
    image: mysql:5.7

    cap_add:
      - SYS_NICE

    environment:
      - MYSQL_ROOT_PASSWORD=database
      - MYSQL_DATABASE=database

    ports:
      - '3306:3306'

    volumes:
      - 'mysql-data:/var/lib/mysql'
